# Changes here will be overwritten by Copier.
_commit: 1.8.1
_src_path: gh:pawamoy/copier-uv
author_email: vandy.goel23@gmail.com
author_fullname: Vandit Goel
author_username: vandyG
copyright_date: '2025'
copyright_holder: Vandit Goel
copyright_holder_email: vandy.goel23@gmail.com
copyright_license: MIT
insiders: false
project_description: Chess Analysis
project_name: chessticles
python_package_command_line_name: chessticles
python_package_distribution_name: chessticles
python_package_import_name: chessticles
repository_name: chessticles
repository_namespace: vandyG
repository_provider: github.com

